---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: default
  labels:
    app: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-test
  template:
    metadata:
      labels:
        app: vault-test
    spec:
      containers:
      - name: httpd-v2
        image: httpd
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: alpha
              key: philosopher
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beta
              key: god
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "31Mi"
            cpu: "60m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20