# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: example
#   namespace: default
# spec:
#   schedule: '*/1 * * * *'
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           serviceAccountName: vault-serviceaccount
#           volumes:
#           - name: vault-token
#             emptyDir:
#               medium: Memory
#           initContainers:
#             - name: vault-kubernetes-authenticator
#               image: postfinance/vault-kubernetes-authenticator
#               imagePullPolicy: Always
#               volumeMounts:
#                 - name: vault-token
#                   mountPath: /home/vault
#               env:
#                 - name: VAULT_ADDR
#                   value: http://192.168.33.10:8200
#                 - name: VAULT_ROLE
#                   value: vault-demo-role
#                 - name: VAULT_TOKEN_PATH
#                   value: /home/vault/.vault-token
#           containers:
#             - name: vault-kubernetes-synchronizer
#               image: postfinance/vault-kubernetes-synchronizer
#               imagePullPolicy: Always
#               volumeMounts:
#                 - name: vault-token
#                   mountPath: /home/vault
#               env:
#                 - name: VAULT_ADDR
#                   value: http://192.168.33.10:8200
#                 - name: VAULT_ROLE
#                   value: vault-demo-role
#                 - name: VAULT_TOKEN_PATH
#                   value: /home/vault/.vault-token
#                 - name: VAULT_SECRETS
#                   value: secret/demo/greek/
#           restartPolicy: OnFailure


---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-kubernetes-authenticator-demo
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: vault-serviceaccount
      restartPolicy: Never
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: configmap-volume
        configMap:
          defaultMode: 0700
          name: my-configmap
      initContainers:
      - name: vault-kubernetes-authenticator
        image: postfinance/vault-kubernetes-authenticator
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vagrant/vault
        env:
        - name: VAULT_ADDR
          value: "http://192.168.33.10:8200"
        - name: VAULT_ROLE
          value: vault-demo-default
        - name: VAULT_TOKEN_PATH
          value: /home/vagrant/vault/.vault-token
      containers:
      - name: alpine
        image: ig0r0k/consul-template:v1
        command:
        - /bin/entrypoint.sh
        env:
        - name: VAULT_ADDR
          value: "192.168.33.10:8200"
        volumeMounts:
        - name: configmap-volume
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - name: vault-token
          mountPath: /home/vagrant/vault
